# Site
name: 'Viet News'
description: 'Phương tiện truyền thông Việt Nam'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'vietnam-news-media'
email: 'mjobmarketcom@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Nguyễn Văn Anh
      site:           https://www.vietnamscoop.com
      avatar:         "https://i.ibb.co/x8KRqM7f/avatar1.jpg"
      bio:            "Nhà báo chuyên về công nghệ và xã hội."
      email:          hi@vietnamscoop.com
      twitter:        https://x.com/VietnamScoop

    jane:
      name:           Trần Thùy Linh
      site:           https://vietnam.net24.news
      avatar:         "https://i.ibb.co/M5KPyXzv/avatar2.jpg"
      bio:            "Biên tập viên và nhà nghiên cứu văn hóa."
      email:          vip@vietnamscoop.com
      twitter:        https://x.com/VietnamScoop    
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: "https://i.ibb.co/M5KPyXzv/avatar2.jpg"
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
